"""add unique consrtains

Revision ID: 3f8a931f76e0
Revises: 79a52f23e99e
Create Date: 2024-07-04 22:09:49.611295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8a931f76e0'
down_revision: Union[str, None] = '79a52f23e99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'article', ['query_id'])
    op.create_unique_constraint(None, 'query', ['title', 'src_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query', type_='unique')
    op.drop_constraint(None, 'article', type_='unique')
    # ### end Alembic commands ###
