"""add image to article

Revision ID: aaf7aa4bc11d
Revises: 68d95d7db607
Create Date: 2024-07-03 22:51:56.280072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf7aa4bc11d'
down_revision: Union[str, None] = '68d95d7db607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'image')
    # ### end Alembic commands ###
