"""add src_url to query

Revision ID: c78c0a0472fa
Revises: aaf7aa4bc11d
Create Date: 2024-07-03 23:34:05.218667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78c0a0472fa'
down_revision: Union[str, None] = 'aaf7aa4bc11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('src_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'src_url')
    # ### end Alembic commands ###
